---
name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'

concurrency:
  group: '${{ github.workflow }} - ${{ github.head_ref || github.ref }}'
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

env:
  PRIMARY_NODE_VERSION: 20

jobs:
  install:
    name: Checkout and Install
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install
        uses: ./.github/actions/prepare-install
        with:
          node-version: ${{ env.PRIMARY_NODE_VERSION }}

  build:
    name: Build All Projects
    runs-on: ubuntu-latest
    needs: [install]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install
        uses: ./.github/actions/prepare-install
        with:
          node-version: ${{ env.PRIMARY_NODE_VERSION }}
      - name: Build
        uses: ./.github/actions/prepare-build

  format:
    name: Verify Format
    runs-on: ubuntu-latest
    needs: [install]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install
        uses: ./.github/actions/prepare-install
        with:
          node-version: ${{ env.PRIMARY_NODE_VERSION }}
      - name: Run check
        run: npm run format:check

  lint_with_build:
    name: Verify Format
    runs-on: ubuntu-latest
    needs: [build]
    strategy:
      matrix:
        lint-task: ['lint:lib', 'lint:demo']
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install
        uses: ./.github/actions/prepare-install
        with:
          node-version: ${{ env.PRIMARY_NODE_VERSION }}
      - name: Build
        uses: ./.github/actions/prepare-build
      - name: Run check
        run: npm run ${{ matrix.lint-task }}

  unit_tests:
    name: Run Unit Tests
    needs: [build]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        # just run on the oldest and latest supported versions and assume the intermediate versions are good
        node-version: [18, 20]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install
        uses: ./.github/actions/prepare-install
        with:
          node-version: ${{ matrix.node-version }}
      - name: Build
        uses: ./.github/actions/prepare-build
      - name: Run Unit Tests
        run: npm run demo:test-ci

  publish_pages:
    name: Publish pages
    runs-on: ubuntu-latest
    needs: [format, lint_with_build, unit_tests]
    if: ${{ github.ref == 'refs/heads/master' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install
        uses: ./.github/actions/prepare-install
        with:
          node-version: ${{ env.PRIMARY_NODE_VERSION }}
      - name: Build
        uses: ./.github/actions/prepare-build
      - name: Run Build Demo
        run: npm run demo:build:prod
      - name: Publish pages
        run: npm run publish-pages
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
