name: publish

on:
  release:
    types: [created]

env:
  PRIMARY_NODE_VERSION: 24

jobs:
  publish:
    name: Publish to NPM
    runs-on: ubuntu-latest
    environment: npm-publish
    permissions:
      id-token: write # Required for trusted publishing
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install
        uses: ./.github/actions/prepare-install
        with:
          node-version: ${{ env.PRIMARY_NODE_VERSION }}
          registry-url: 'https://registry.npmjs.org'
      - name: Build
        uses: ./.github/actions/prepare-build
      - name: Copy README to package
        run: npm run copy-readme
      - name: Remove NODE_AUTH_TOKEN
        run: |
          unset NODE_AUTH_TOKEN
          npm whoami
      - name: Publish to NPM packages
        run: cd dist/lib && npm publish --access public --provenance
        env:
          NPM_CONFIG_PROVENANCE: 'true'
