name: publish

on:
  release:
    types: [created]

env:
  PRIMARY_NODE_VERSION: 24

jobs:
  publish:
    name: Publish to NPM
    runs-on: ubuntu-latest
    environment: npm-publish
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install
        uses: ./.github/actions/prepare-install
        with:
          node-version: ${{ env.PRIMARY_NODE_VERSION }}
          registry-url: 'https://registry.npmjs.org'
      - name: Build
        uses: ./.github/actions/prepare-build
      - name: Copy README to package
        run: npm run copy-readme
      - name: Publish to NPM packages
        run: cd dist/lib && npm publish --ignore-scripts --access public
